name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  framework-ci:
    uses: while-one/caffeine-build/.github/workflows/reusable-ci.yml@main
    with:
      submodules: recursive
